version: '2'

services:

  test-us-admin:
    build: ./
    networks:
      - us-admin
    cap_add:
      - NET_ADMIN

  test-us-staging:
    build: ./
    networks:
      - us-staging
    cap_add:
      - NET_ADMIN

  test-us-dev:
    build: ./
    networks:
      - us-dev
    cap_add:
      - NET_ADMIN

  test-eu-admin:
    build: ./
    networks:
      - eu-admin
    cap_add:
      - NET_ADMIN

  test-eu-staging:
    build: ./
    networks:
      - eu-staging
    cap_add:
      - NET_ADMIN

  test-eu-dev:
    build: ./
    networks:
      - eu-dev
    cap_add:
      - NET_ADMIN

  eu-admin-router:
    container_name: eu-admin-router
    image: iwaseyusuke/quagga-alpine:latest
    hostname: eu-admin-router
    command:
      - "ospfd"
      - "bgpd"
    volumes:
      - "./eu-admin-router/:/etc/quagga/"
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      eu-admin:
        ipv4_address: 192.168.50.254
      eu-interco1:
        ipv4_address: 192.168.10.5
      eu-interco2:
        ipv4_address: 192.168.10.14
      interregion1:
        ipv4_address: 10.254.1.5

  eu-staging-router:
    container_name: eu-staging-router
    hostname: eu-staging-router
    command:
      - "ospfd"
      - "bgpd"
    privileged: true
    tty: true
    volumes:
      - "./eu-staging-router/:/etc/quagga/"
    image: iwaseyusuke/quagga-alpine:latest
    cap_add:
      - ALL
    networks:
      eu-staging:
        ipv4_address: 192.168.51.254
      eu-interco1:
        ipv4_address: 192.168.10.6
      eu-interco3:
        ipv4_address: 192.168.10.22

  eu-dev-router:
    container_name: eu-dev-router
    hostname: eu-dev-router
    command:
      - "ospfd"
      - "bgpd"
    tty: true
    volumes:
      - "./eu-dev-router/:/etc/quagga/"
    privileged: true
    image: iwaseyusuke/quagga-alpine:latest
    cap_add:
      - ALL
    networks:
      eu-dev:
        ipv4_address: 192.168.52.254
      eu-interco2:
        ipv4_address: 192.168.10.13
      eu-interco3:
        ipv4_address: 192.168.10.21

  us-admin-router:
    container_name: us-admin-router
    image: iwaseyusuke/quagga-alpine:latest
    hostname: us-admin-router
    command:
      - "ospfd"
      - "bgpd"
    volumes:
      - "./us-admin-router/:/etc/quagga/"
    privileged: true
    tty: true
    cap_add:
      - ALL
    networks:
      us-admin:
        ipv4_address: 192.168.150.254
      us-interco1:
        ipv4_address: 192.168.20.5
      us-interco2:
        ipv4_address: 192.168.20.14
      interregion1:
        ipv4_address: 10.254.1.6

  us-staging-router:
    container_name: us-staging-router
    hostname: us-staging-router
    command:
      - "ospfd"
      - "bgpd"
    privileged: true
    tty: true
    volumes:
      - "./us-staging-router/:/etc/quagga/"
    image: iwaseyusuke/quagga-alpine:latest
    cap_add:
      - ALL
    networks:
      us-staging:
        ipv4_address: 192.168.151.254
      us-interco1:
        ipv4_address: 192.168.20.6
      us-interco3:
        ipv4_address: 192.168.20.22

  us-dev-router:
    container_name: us-dev-router
    hostname: us-dev-router
    command:
      - "ospfd"
      - "bgpd"
    privileged: true
    tty: true
    volumes:
      - "./us-dev-router/:/etc/quagga/"
    image: iwaseyusuke/quagga-alpine:latest
    cap_add:
      - ALL
    networks:
      us-dev:
        ipv4_address: 192.168.152.254
      us-interco2:
        ipv4_address: 192.168.20.13
      us-interco3:
        ipv4_address: 192.168.20.21

networks:
  eu-admin:
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
  eu-staging:
    ipam:
      driver: default
      config:
        - subnet: 192.168.51.0/24
  eu-dev:
    ipam:
      driver: default
      config:
        - subnet: 192.168.52.0/24
  us-admin:
    ipam:
      driver: default
      config:
        - subnet: 192.168.150.0/24
  us-staging:
    ipam:
      driver: default
      config:
        - subnet: 192.168.151.0/24
  us-dev:
    ipam:
      driver: default
      config:
        - subnet: 192.168.152.0/24
  interregion1:
    ipam:
      driver: default
      config:
        - subnet: 10.254.1.0/29
  eu-interco1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/29
  eu-interco2:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.8/29
  eu-interco3:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.16/29
  us-interco1:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/29
  us-interco2:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.8/29
  us-interco3:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.16/29
